apiVersion: v2
name: cert-manager
description: A wrapper Helm chart for cert-manager
type: application
version: 0.1.0
appVersion: "v1.21.1"

dependencies:
  - name: cert-manager
    version: 1.21.1
    repository: https://charts.jetstack.io
